// Add any additional repositories for your dependencies here.

repositories {
    maven {url = uri("https://jitpack.io")}
    maven {
        name = "GTNH Maven"
        url = "https://nexus.gtnewhorizons.com/repository/releases/"
    }
    maven {
        name = "SpongePowered"
        url = "https://repo.spongepowered.org/repository/maven-public/"
    }
}
